Use Gradle Catalog to manage lib versions.
ivanisidrowu/KtRssReader pull request #77
Opened 2022-07-27 09:50 UTC by dev-weiqi

2022-07-28 02:52 UTC, AmyPlace approved these changes
LGTM

2022-07-28 03:19 UTC, ivanisidrowu approved these changes
Good job!

2022-07-28 04:03 UTC, lush-life requested changes

2022-07-29 02:05 UTC, dev-weiqi commented on buildSrc/src/main/java/Version.kt
> +    const val compileSdk = 31
Also upgrade target sdk version to 31!

2022-07-29 02:08 UTC, dev-weiqi commented on android/build.gradle.kts
> +            artifactId = "KtRssReader"
Our artifact id is uppercase now 🤣

![截圖 2022-07-29 10 07 11](https://user-images.githubusercontent.com/55677874/181667878-0bf6c644-7578-4c73-983f-d54885b54d46.png)

2022-07-29 02:39 UTC, lush-life commented on buildSrc/src/main/java/Version.kt
> +    const val compileSdk = 31
[Suggestion] Upgrade major version of buildTool that equals to compileSdk version

2022-07-29 06:42 UTC, dev-weiqi commented on buildSrc/src/main/java/Version.kt
> +    const val compileSdk = 31
Done!

2022-07-29 07:01 UTC, lush-life approved these changes

2022-07-29 07:03 UTC, lush-life commented on buildSrc/src/main/java/Version.kt
> +    const val compileSdk = 31
👍

2022-08-02 13:24 UTC, merged